### ISSUE TITLE
[프론트엔드] <SideBar> 일반 로그인  기능 구현

### ISSUE THREAD

**Issue by soyoung931014** [codestates/Dajavas#13]
## ISSUE
- Group: `client`
- Type:  `feature`
- Detail: `Side Bar: 일반 로그인 페이지`
  

## TODO
- [ ] 페이지 로그인: 토큰요청
  post/ {email, password}
- [ ] 토큰 상태 변경
- [ ] 로그인 상태 변경

## Labels
Estimated time: E: `3hs`
Group : `client`
Sprint: `Sprint 2`
Urgency: `bare`
