### ISSUE TITLE
[프론트엔드] <NavBar> 기록 <FishBoard> 기록 기능(CRUD) 구현

### ISSUE THREAD

**Issue by soyoung931014** [codestates/Dajavas#63]
## ISSUE
- Group: `client`
- Type:  `feature`
- Detail: ` <NavBar>  기록 <FishBoard> 기록 CRUD기능`
  

## TODO
- [ ] 유저에 따른 기록 리스트 get요청
- [ ] 기록 수정 put 요청
- [ ]  기록 삭제 delete 요청
- [ ]  기록하기 버튼
- [ ]  사진, 어종, 크기 입력창
- [ ] 입력정보 저장 post요청

## Labels
Estimated time: E: `3hs`
Group : `client`
Sprint: `Sprint `
